export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  SIGN_UP: '/signup',
  COMING_SOON_USER: '/dashboard/user/coming-soon',
  COMING_SOON_ADMIN: '/dashboard/admin/coming-soon',
  USER_DASHBOARD: '/dashboard/user',
  USER_DASHBOARD_REQUEST: '/dashboard/user/request',
  ADMIN_DASHBOARD: '/dashboard/admin',
  ADMIN_DASHBOARD_PAYS: '/dashboard/admin/pays',
  ADMIN_DASHBOARD_DEMANDES: '/dashboard/admin/demandes',
  ADMIN_DASHBOARD_USERS: '/dashboard/admin/users',
  USER_DIRECTIONS_BOOK: '/dashboard/user/directions-book',
  USER_DOCUMENTS: '/dashboard/user/documents',
  USER_PROFILE: '/dashboard/user/account',
  CERTIFICATE_DETAIL: '/dashboard/certificate-detail',
  USER_DASHBOARD_REQUEST_PARAMS: '/dashboard/user/request?certificateId=',
  USER_MARKETPLACE:'/dashboard/user/marketplace',
  ADMIN_MARKETPLACE:'/dashboard/admin/marketplace',
};
