import React, { FC } from 'react';
import MUIHead from 'next/head';

type Props = {
  title: string;
};

export const Head: FC<Props> = ({ title }) => {
  return (
    <MUIHead>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </MUIHead>
  );
};
